# Generated by Django 3.1.3 on 2020-11-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='topping',
        ),
    ]
